### ISSUE TITLE
Translation into other languages

### ISSUE THREAD

**Issue by Cvcdss** [AcclaimedAP/Cat-Hero-Idle-RPG-tools-Frontend#124]
Hi [Cvcdss],

I hope you’re doing well. I sometimes have difficulty understanding certain words in English, and I believe it would be better for a good number of games to have translations in Portuguese and Spanish. This way, everyone would have a better experience. I would really appreciate your help!

Thank you so much!

Best regards,
[Cvcdss]

**Comment by AcclaimedAP** [comment]
So you'd like the site to have the option to display the content in other languages?

I don't think the idea is bad in itself, but I don't think we have the ability to do this easily right now. Not only would it require a bit of work to just implement the functionality, but we would also need to grab all translations for every companion, skill, and rune that we want to support, and make sure it also gets updated as more stuff is added in the future. The maintenance to add new stuff is already fairly convoluted.

**Comment by Matteo-Ynov** [comment]
Hey Cvcdss, unfortunately the project was not thought for i18n and it would be hard to just slap it in now. I would advise to use your browser integrated translator or see it as a way to improve your English 😄

**Comment by Cvcdss** [comment]
I completely understand the level of complexity involved. It’s a considerable amount of work, both in terms of implementation and ongoing maintenance for translations. It’s important to prioritize what we can effectively manage at this time. If the opportunity arises to explore this feature in the future, that would be great, but for now, it’s perfectly fine as is.

**Comment by Cvcdss** [comment]
I appreciate the support you’ve offered, and I want to acknowledge the wonderful work you’re doing on the game. I’m also looking forward to improving my English a bit. Thank you for all your efforts!
